[package]
name = "aether"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.37.0"
winit = "0.27.0"
shaderc = "0.8.0"
cstr = "0.2.10"
eyre = "0.6.8"
