[package]
name = "arbiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aether = { path = "../aether" }
winit = "0.27.0"
ash = "0.37.0+1.3.209"
