[package]
name = "arbiter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aether = { path = "../aether" }
winit = "0.26.0"
vulkano = "0.30.0"
vulkano-shaders = "0.30.0"
bytemuck = "1.12.0"
